version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: goweb_db
    environment:
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:8080"
    volumes:
      - ./data/database/postgres:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    container_name: goweb_adm
    ports:
      - "8081:8080"
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    # external: true
